{
    "cells": [
        {
            "cell_type": "code",
            "execution_count": 2,
            "metadata": {},
            "outputs": [
                {
                    "name": "stderr",
                    "output_type": "stream",
                    "text": [
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 34, in <module>\n",
                        "    chain.run(\"Where does Winston live?\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 287, in __call__\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 34, in <module>\n",
                        "    chain.run(\"Where does Winston live?\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 136, in _call\n",
                        "    docs = self._get_docs(question, run_manager=_run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 216, in _get_docs\n",
                        "    return self.retriever.get_relevant_documents(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/schema/retriever.py\", line 186, in get_relevant_documents\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 34, in <module>\n",
                        "    chain.run(\"Where does Winston live?\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 139, in _call\n",
                        "    answer = self.combine_documents_chain.run(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 510, in run\n",
                        "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 287, in __call__\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 34, in <module>\n",
                        "    chain.run(\"Where does Winston live?\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 139, in _call\n",
                        "    answer = self.combine_documents_chain.run(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 510, in run\n",
                        "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py\", line 122, in _call\n",
                        "    output, extra_return_dict = self.combine_docs(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py\", line 171, in combine_docs\n",
                        "    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/llm.py\", line 298, in predict\n",
                        "    return self(kwargs, callbacks=callbacks)[self.output_key]\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 287, in __call__\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 34, in <module>\n",
                        "    chain.run(\"Where does Winston live?\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 139, in _call\n",
                        "    answer = self.combine_documents_chain.run(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 510, in run\n",
                        "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py\", line 122, in _call\n",
                        "    output, extra_return_dict = self.combine_docs(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py\", line 171, in combine_docs\n",
                        "    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/llm.py\", line 298, in predict\n",
                        "    return self(kwargs, callbacks=callbacks)[self.output_key]\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/llm.py\", line 108, in _call\n",
                        "    response = self.generate([inputs], run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/llm.py\", line 120, in generate\n",
                        "    return self.llm.generate_prompt(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chat_models/base.py\", line 459, in generate_prompt\n",
                        "    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chat_models/base.py\", line 319, in generate\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 35, in <module>\n",
                        "    chain.run(\"Describe Victory Mansions\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 287, in __call__\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 35, in <module>\n",
                        "    chain.run(\"Describe Victory Mansions\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 136, in _call\n",
                        "    docs = self._get_docs(question, run_manager=_run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 216, in _get_docs\n",
                        "    return self.retriever.get_relevant_documents(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/schema/retriever.py\", line 186, in get_relevant_documents\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 35, in <module>\n",
                        "    chain.run(\"Describe Victory Mansions\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 139, in _call\n",
                        "    answer = self.combine_documents_chain.run(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 510, in run\n",
                        "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 287, in __call__\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 35, in <module>\n",
                        "    chain.run(\"Describe Victory Mansions\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 139, in _call\n",
                        "    answer = self.combine_documents_chain.run(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 510, in run\n",
                        "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py\", line 122, in _call\n",
                        "    output, extra_return_dict = self.combine_docs(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py\", line 171, in combine_docs\n",
                        "    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/llm.py\", line 298, in predict\n",
                        "    return self(kwargs, callbacks=callbacks)[self.output_key]\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 287, in __call__\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2072, in _configure\n",
                        "    handler = LangChainTracer(project_name=tracer_project)\n",
                        "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 97, in __init__\n",
                        "    self.client = client or get_client()\n",
                        "                            ^^^^^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py\", line 55, in get_client\n",
                        "    _CLIENT = Client()\n",
                        "              ^^^^^^^^\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 272, in __init__\n",
                        "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langsmith/client.py\", line 181, in _validate_api_key_if_hosted\n",
                        "    raise ls_utils.LangSmithUserError(\n",
                        "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
                        "\n",
                        "During handling of the above exception, another exception occurred:\n",
                        "\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
                        "    msg = self.format(record)\n",
                        "          ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 953, in format\n",
                        "    return fmt.format(record)\n",
                        "           ^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 687, in format\n",
                        "    record.message = record.getMessage()\n",
                        "                     ^^^^^^^^^^^^^^^^^^^\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "          ~~~~^~~~~~~~~~~\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
                        "  File \"<frozen runpy>\", line 88, in _run_code\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/traitlets/config/application.py\", line 1046, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 736, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
                        "    res = shell.run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n",
                        "    return super().run_cell(*args, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n",
                        "    result = runner(coro)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n",
                        "    if await self.run_code(code, result, async_=asy):\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/var/folders/db/pyhy3fjj2yl_btysq7v21hn80000gn/T/ipykernel_31434/1871784720.py\", line 35, in <module>\n",
                        "    chain.run(\"Describe Victory Mansions\")\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 505, in run\n",
                        "    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py\", line 139, in _call\n",
                        "    answer = self.combine_documents_chain.run(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 510, in run\n",
                        "    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py\", line 122, in _call\n",
                        "    output, extra_return_dict = self.combine_docs(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py\", line 171, in combine_docs\n",
                        "    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/llm.py\", line 298, in predict\n",
                        "    return self(kwargs, callbacks=callbacks)[self.output_key]\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/base.py\", line 304, in __call__\n",
                        "    self._call(inputs, run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/llm.py\", line 108, in _call\n",
                        "    response = self.generate([inputs], run_manager=run_manager)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chains/llm.py\", line 120, in generate\n",
                        "    return self.llm.generate_prompt(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chat_models/base.py\", line 459, in generate_prompt\n",
                        "    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/chat_models/base.py\", line 319, in generate\n",
                        "    callback_manager = CallbackManager.configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 1479, in configure\n",
                        "    return _configure(\n",
                        "  File \"/Users/jeongdaegyu/Documents/gpt_pratice_dk/env/lib/python3.11/site-packages/langchain/callbacks/manager.py\", line 2075, in _configure\n",
                        "    logger.warning(\n",
                        "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
                        "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n"
                    ]
                },
                {
                    "data": {
                        "text/plain": [
                            "'Victory Mansions is the building where Winston Smith lives. It is a run-down, dilapidated apartment complex that is part of the city of Airstrip One in Oceania. The building is described as having a hallway that smells of boiled cabbage and old rag mats. The elevator is often not working due to power outages, and there is a large poster of the face of Big Brother watching over the residents. The building is in disrepair, with rotting nineteenth-century houses, patched windows, and sagging garden walls surrounding it. Overall, Victory Mansions is portrayed as a grim and depressing place to live.'"
                        ]
                    },
                    "execution_count": 2,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "from langchain.chat_models import ChatOpenAI\n",
                "from langchain.document_loaders import UnstructuredFileLoader\n",
                "from langchain.text_splitter import CharacterTextSplitter\n",
                "from langchain.embeddings import OpenAIEmbeddings, CacheBackedEmbeddings\n",
                "from langchain.vectorstores import FAISS\n",
                "from langchain.storage import LocalFileStore\n",
                "from langchain.chains import RetrievalQA\n",
                "\n",
                "llm = ChatOpenAI()\n",
                "\n",
                "cache_dir = LocalFileStore(\"./.cache/\")\n",
                "\n",
                "splitter = CharacterTextSplitter.from_tiktoken_encoder(\n",
                "    separator=\"\\n\",\n",
                "    chunk_size=600,\n",
                "    chunk_overlap=100,\n",
                ")\n",
                "loader = UnstructuredFileLoader(\"../files/chapter_one.txt\")\n",
                "\n",
                "docs = loader.load_and_split(text_splitter=splitter)\n",
                "\n",
                "embeddings = OpenAIEmbeddings()\n",
                "\n",
                "cached_embeddings = CacheBackedEmbeddings.from_bytes_store(embeddings, cache_dir)\n",
                "\n",
                "vectorstore = FAISS.from_documents(docs, cached_embeddings)\n",
                "\n",
                "chain = RetrievalQA.from_chain_type(\n",
                "    llm=llm,\n",
                "    chain_type=\"stuff\",\n",
                "    retriever=vectorstore.as_retriever(),\n",
                ")\n",
                "# retriever은 vectorstoe에서 가져와도 되지만 invoke등을 통해 가져올 수 도 있음\n",
                "chain.run(\"Where does Winston live?\")\n",
                "chain.run(\"Describe Victory Mansions\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "env",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.11.6"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}
